services:
  - type: web
    name: tour
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py loaddata App/fixtures/destinations.json
    startCommand: gunicorn journy.wsgi
