# Generated by Django 3.2.25 on 2025-01-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20250102_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='image',
        ),
        migrations.AddField(
            model_name='destination',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
