# Generated by Django 3.2.25 on 2025-01-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20250110_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='image_path',
        ),
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='destination_images'),
        ),
    ]
