# Generated by Django 3.2.25 on 2025-01-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date']},
        ),
    ]
