# Generated by Django 3.2.25 on 2025-01-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['id']},
        ),
    ]
