# Generated by Django 3.2.25 on 2025-01-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_package_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
