# Generated by Django 3.2.25 on 2025-02-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='banking_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
