# Generated by Django 5.1.7 on 2025-03-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_traveller'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='country_code',
            field=models.CharField(default='+91', max_length=10),
        ),
    ]
