# Generated by Django 5.1.7 on 2025-03-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_traveller_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='phone',
            field=models.CharField(default='Not Provided', max_length=15),
        ),
    ]
