# Generated by Django 5.1.7 on 2025-03-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_remove_traveller_user_id_traveller_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
