# Generated by Django 4.2.23 on 2025-08-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_company_has_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
