# Generated by Django 4.2.23 on 2025-08-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='blog_images/default-blog.jpg', null=True, upload_to='blog_images'),
        ),
    ]
