# Generated by Django 4.2.23 on 2025-08-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='travel_types/')),
                ('description', models.TextField()),
            ],
        ),
    ]
