# Generated by Django 5.1.7 on 2025-03-19 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminphase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='country_code',
            field=models.CharField(default='+91', max_length=10),
        ),
        migrations.AddField(
            model_name='traveller',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traveller',
            name='name',
            field=models.CharField(default='Unknown Traveller', max_length=255),
        ),
        migrations.AddField(
            model_name='traveller',
            name='phone',
            field=models.CharField(default='Not Provided', max_length=15),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending')], max_length=50),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='tour_type',
            field=models.CharField(choices=[('Solo', 'Solo'), ('Group', 'Group')], max_length=50),
        ),
    ]
