# Generated by Django 5.1.7 on 2025-03-19 10:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminphase', '0002_traveller_country_code_traveller_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
